version: '3'
services:
  php_telnet_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./output.txt:/TELNET

  telnet_server:
    build:
      context: .
      dockerfile: Dockerfile_telnet
    ports:
      - "23:23"